[package]
name = "lib-store"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-stage = { path = "../lib-stage" }
lib-calculator = { path = "../lib-calculator" }
thiserror = "2.0.11"
serde = "1.0.217"
serde_json = "1.0.135"

[dependencies.mongodb]
version = "3.1.1"
features = ["sync"]