[package]
name = "lib-stage"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-store = { path = "../lib-store" }

ndarray = { version = "0.16.1", features = ["rayon"] }
csv = "1.3.1"
rayon = "1.10.0"
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
